export default {
    all: 'All',
    submit: 'Submit',
    please_select: 'Please select',
    search: 'Search',
    confirm: 'Confirm',
    searchs: 'Search',
    disclaimer: 'Disclaimer',
    got_it: 'Got it',
    please_enter: 'Please enter',
    close: 'Close',
    information: 'Information',
    cancel: 'Cancel',
    copy: 'Copy',
    delete: 'Delete',
    copy_link: 'Copy Link',
    loading: 'Loading',
    waiting: 'Waiting',
    uploading: 'Uploading',
    copy_successful: 'Copied successfully',
    save_successful: 'Saved successfully',
    edit_successful: 'Modified successfully',
    server_error: 'Server error, please try again later',
    tips: 'Tips',
    con_tips: 'Previously tested version U',
    download_pic_tip: 'Download the picture and save it to the album',
    tips_txt:"We found that you copied a link/an item, would you like to open it for you?",
    open_line:"Open",
    Unable:"Unable to capture product information",
    refresh:'Refresh',
    Manual_filling:"Manual filling",
    hot:'hot',
    no_more:"No more",
};
