export default {
    product_details: 'Product details',
    after_sales_service: 'After Sales Service',
    buy_now: 'Buy Now',
    add_to_cart: 'Add To Cart',
    collect: 'Collect',
    affiliate_share: 'Affiliate Share',
    sales: 'Sales',
    product_link: 'Product Link',
    edit: 'Edit',
    domestic_freight: 'Domestic Freight',
    quantity: 'Quantity',
    available: 'Available',
    remark_placeholder: `Write a message ONLY when you have special requirements regarding this order's purchasing.`,
    purchase_tip:
        'Kilyimall will only purchase for you according to the link you enter. If you have any doubts regarding your orders, reach out to our online service.',
    fav_successful: 'Collection successful',
    please_select_sku: 'Please select a specification',
    add_successful: 'Added successfully',
    note_1: 'The goods you purchased will be delivered to the Kilyimall warehouse . When the goods arrive at the warehouse, we will check and take photos for you.',
    note_2: 'You can view and manage items in the warehouse.',
    note_3: 'If you are not satisfied with the goods after they arrive at the Kilyimall warehouse, you can apply for a return within 5 days. Our buyer will negotiate with the seller on behalf of you to deal with after-sale issues. ',
    seller_to_Kilyimall: 'From the seller\n to the Kilyimall',
    Kilyimall_to_you: 'From Kilyimall\n to You',
    pay_for_order: 'Pay for order',
    pay_for_package: 'Pay for package',
    delivery_of_parcels: 'Delivery of parcels',
    rating: 'Rating',
    check_out_store: 'Check out the store',
    store_sales_ranking: 'Sales Ranking of Our Store',
    sold: 'Sold',
    pieces: 'pieces',
    modify_price_tip:
        'If there is a price discount on the website, click to modify it',
    modify_the_price: 'Modify the price',
    enter_price: 'Please enter the price',
    confirm_modify_price: 'Confirmation of revised price',
    modify_price_reason_note:
        'Please note clearly the reason for price modification. if the submitted price is inconsistent with the actual price, you will be required to make up the difference.',
    select_modify_price_reason:
        'Please select the reason why you want to modify the price:',
    reason_1: 'Store full discount or receive coupon',
    reason_2:
        'full discount free shipping or combined delivery with the previous order, free shipping.',
    reason_3: 'Designated set price is available for package',
    reason_4:
        'There is a special price. it is not in line with the current price.',
    reason_5:
        'Offer negotiated with the seller using a personal account number',
    item_details_discount_time: 'Active remaining time',
    'item_details_discount': 'Shop Discount',
    item_details_send_discount: 'Deduct Int\'l Shipping',
    item_details_send_discount_end: 'Shipping Fee Deduction Expire Time',
    item_details_discount_rules: 'Activity rules',
    item_details_discount_rules_desc1: 'Submit this product before the deadline to send international packages, can offset',
    item_details_discount_rules_desc2: 'international freight, offset up to the package freight ',
    item_details_discount_rules_desc3: ', can be used in addition to other credit products, can be used with package coupons and system discounts.',
    item_details_refresh: 'Refresh',
    item_details_qc_tip1: 'Growth value is equal to or greater than',
    item_details_qc_tip2: ', you can see the product reference map. Your current growth value is insufficient.',

    qcPic: 'QC Picture ',
    Source_product: "Source of the product",
	Kilyimallto_purchase: 'Kilyimall can entrust buyers to purchase for you',
	find_similarity: 'Find similarity',
};
