export default {
    beginner_guide: `Beginner's Guide`,
    shipping_fee_estimation: 'Estimate',
    affiliates: 'Affiliates',
    notmake: "Fill & Buy",
    transfer_order: 'Transfer order',
    search_placeholder: 'Taobao,Tmall,1688,JD,Weidian Product URL or Keywords',
    more: 'More',
    camera: 'Take a photo',
    album: 'Upload a picture',
    everyone_buy: 'Everyone is buying',
    load_more: 'Load more',
    latest: 'Latest',
    news: ' News',
    Default_sort:"Default sort",
    not_find:"Sorry, we can't find this item",
    dl_tips: 'Shop anytime, shop anywhere!',
	get: 'GET',
};
