export default {
	link_tip: 'The links you submit on this page belong to third-party product links (such as: Xianyu, XiaoHongshu, Bilibili, yupoo, etc.), Kilyimall can only help you find the linked merchants for product consultation, purchase and arrange third-party logistics delivery services. Kilyimall is unable to identify the quality and authenticity of goods and requires you to bear the relevant risk before placing an order.',
	bank_link_title: 'Fill in the product link',
	bank_link_place: 'Please enter the product link and start with http:// or https://',
	shop_name: 'Trade name',
	shop_name_place: 'Please fill in the product name',
	shop_specification: 'Commodity specification',
	shop_specification_place: 'In order to purchase items for you more accurately, please leave the color/size rule information here. You can also add reference images.',
	upload_img: 'Upload pictures',
	send_to: 'Send to',
	send_to_place: 'Please select',
	goods_money: 'Unit price of goods',
	goods_money_place: 'Please fill in the unit price',
	goods_number: "Commodity quantity",
	arrive_money: "Freight to warehouse",
	arrive_money_place: "Please fill in the freight to warehouse",
	freight: 'Freight Estimate >',
	total_price: 'Estimated total price:',
	price_tip: 'The price does not include international shipping charges',
	agree_check: 'I agree',
	instructions: '《Instructions for Purchasing Agents》',
	service: '《After-sales service》',
	submit: 'Submit',
	incorrect_link: 'Incorrect link',
	item_notfound_agree_checkbox: 'Please click I have read and agree',
	purchase_order:"Fill in the purchase order",
	reupload:"Reupload",
	modal_content:"Kilyiuy is unable to determine the price of the goods on the third-party platform, so you need to enter the price below. If you are not clear about the price of the goods, you can fill in 1 yuan to place an order. After receiving the order, Kilyiuy buyer will contact the merchant and then initiate the product supplement to you.",
	Expense_correlation:"Expense correlation",
	friendly_reminder:"Friendly reminder",
	limited:"The size of a single image is limited to 3M (gif, jpg, png formats are supported)",
	special_procurement:"Messages for procurement, no special procurement requirements do not write",
	procurement_requirements:"Please fill in the seller's shipping cost to Kilyimall warehouse",
	commodity_details:"Commodity details",
	confirmText:"Confirm",
	conversion_standard:'Total amount = Cost of goods + freight to warehouse conversion standard (based on RMB)'
}
