export default {
    language: 'Language',
    currency: 'Currency',
    account_security: 'Account security',
    card_billing_address: 'Card billing address',
    theme: 'Theme',
    language_2: 'Language',
    currency_2: 'Currency',
    about: 'About',
    logout: 'Log out',
    select_theme: 'Theme',
    light: 'Light',
    dark: 'Dark',
    account_binding: 'Account binding',
    make_up_authorization: 'Make-up authorization',
    custom_photography_template: 'Custom photography template',
    email_and_app_push: 'Email & APP Push Notifications',
    account_cancellation: 'Delete Account',
	equipment:'Equipment',
	Undo_successfully:'Undo successfully',
	Client_information:"Client information",
	Login_location:"Login location",
	login_time:"Login time",
	login_IP:"Login IP",
	current_device:"Current device",
	will_be_revoked:"The device account information will be revoked",
	Whether_to_revoke_access:"Whether to revoke access",
	Revoke_access:'Revoke access',
	Choose_one:"Please select at least one",
    reason_for_account_cancellation: 'Reason for account cancellation',
    reason_1: 'Security / Privacy Issues',
    reason_2: 'Poor customer service',
    reason_3: 'The cost is too high',
    reason_4: 'Complex shopping process',
    reason_5: 'Other reasons',
    enter_reason: 'Enter the reason for closing your account',

    // 关于Kilyimall
    service_terms: 'Service Terms',
    privacy_policy: 'Privacy Policy',

    // 注销提示
    cancellation_title: 'Applying to delete account',
    cancellation_content: 'Submitting an application to delete an account will enter a 7-day cooldown period to prevent users from accidentally deleting their account. If you log in within 7 days, the system will cancel the deletion of the account',
    cancellation_again_balance: 'Your account balance or order is not completed, please resubmit the cancellation application after processing.',
    cancellation_confirm: 'Your account has entered the cooling off period for deletion. If the user does not log in to the account for 7 days, the account and all data will be deleted from the server after 7 days',

    // 账号绑定
    binding: 'Binding',

    // 补款授权
    domestic_freight_auth: 'Domestic Freight Authorization',
    single_limit: 'Single limit',
    daily_cap: 'Daily cap',
    remaining_amount: 'Remaining amount',
    order_top_up_auth: 'Order top-up authorization',
    international_freight_auth: 'International Freight Authorization',
    My_grade:"My grade",
    View_growth_record:"View growth record",
    Current_level:"Current level",
    Still_need:"Still need",
    Growth_valuess:"Growth value can be upgraded to",
    awarded_according:"Growth value is awarded according to freight amount (1CNY=1 growth value)",
    Growth_value:" Growth value",
    timess:"Time",
    typess:"Type",
    pointss:"Points",
    Relevant_number:"Relevant number",
    achieve_setting:"Achieve",
    Growth_value_reached:"growth value reaches",
    Not_yet_unlocked:"Unlocked",
    Can_be_upgraded:"Can be upgraded",
    haveMoney:"Money",
    completion_time:"Completion time",
    delivery_information_must:'When sending electric goods to Saudi Arabia, the recipient information must be in English.'
};
