export default {
    shipping_fee: 'Shipping Fee',
    transit_time: 'Transit Time',
    price_sort: 'Price',
    delivery_sort: 'Delivery',
    reminder: 'Reminder',
    view_details: 'View details',

    // 寄送线路详情
    days: 'Days',
    first_price: 'First Price',
    continued_weight_price: 'Continued Weight Price',
    operation_fee: 'Operation Fee',
    service_fee: 'Service Fee',
    fuel_surcharge: 'Fuel Surcharge',
    consignee: 'Consignee',
    delivery_situation_title: 'Inquire the package delivery situation',
    delivery_desc: 'Instructions for package delivery',
    progress_title_1: 'All packages shipped during ',
    progress_title_2:
        ', As of today, check the time limit for properly delivered packages ',
    progress_title_3:
        'As of today, check the packages in the delivery period, The logistics track shows the package data in transit and waiting to be picked up.',
    not_delivered: 'Not delivered yet',
    provided_by: 'The data was provided by Kilyimall.com',
    select_date_range: 'Select date range',
    select_end_date: 'Select an end date',
    parcel_restriction: 'Parcel Restriction',
    minimum_weight_limit: 'Minimum weight limit',
    maximum_weight_limit: 'Maximum weight limit',
    size_limit: 'Size limit',
    volume_charging_rules: 'Volume charging rules',
    cannot_send: 'Cannot Send',
    can_send: 'Can send',
    charge_standard: 'Charge Standard',
    customs_declaration_fee: 'Customs declaration fee',
    tax_payment_method: 'Tax payment method',
    features_of_the_route: 'Features of the route',
    basic_features: 'Basic features',
    prohibited_to_send: 'Prohibited to send',
    activity_Status: 'Activity Status',
    start: 'Start',
    end: 'End',
	price_screening: 'Price screening',
};
