export default {
    volume: 'Volume',
    rehearsal_packing: 'Rehearsal Packing',
    remove_packaging_tip:
        'click this button means to check the weight and volume that are removed packaging. However, Kilyimall does not offer this data for products that are with only little packaging since the difference will not be large. Please tick whether to remove packaging/tags for these items on the Parcel Submission page.',
    stored_time: 'Stored Time',
    remove_packaging: 'Remove Packaging',
    weight: 'Weight',
    warehouse_sequencing: 'Warehouse sequencing',
    storage_time_decreasing: 'Storage time decreasing',
    storage_time_increasing: 'Storage time increasing',
    order_time_decreasing: 'Order time decreasing',
    order_time_increasing: 'Order time increasing',
    selected: 'Selected',
    total: 'Total',
    pieces_of_goods: '',
    to: 'To ',
    overdue_goods: 'Overdue goods',
    abandon_goods: 'Abandon goods',
    reward: 'Reward',
    rehearsal_tip_title: 'Tip',
    rehearsal_tip_content:
        'The Kilyimall pre-packaging service is an additional storage service that costs 20 yuan per time. This service can help you pre-package the items to be sent as required. Pre-packaging provides you with accurate package volume/size and accurate weight. We will complete it for you within 24 hours. Would you like to continue?',
    rehearsal_never_tip: 'No more reminders in the future',
    choose:"Choose",
    

    // 提交包裹
    address_empty:'Your address is empty',
    shipping_address:'Select shipping address',
    Put_away:'Put away',
    Unfold:'Unfold',
    product_list: 'Product list',
    remove_tag: 'Remove Tag',
    remove_packaging: 'Remove Packaging',
    packing_details: 'Packing details',
    choose_logistics: 'Choose logistics',
    logistics_explain: 'Logistics Description',
    remark: 'Remark',
    remark_placeholder:
        'Feel free to leave a note here if you have other requirements',
    footer_tip_1: '',
    footer_tip_2: 'free rehearsal, service fee of 20 yuan',
    account: "account:",
    remark_note: "Remark:",
    create_time: "Submission time：",
    ordertosend_insurance_buy: 'Buy Insurance',
    ordertosend_insurance_fee: 'Insurance fee:',
    ordertosend_insurance_rate: 'Insurance rate:',
    ordertosend_insurance_product_amount: 'Product Insured Amount:',
    ordertosend_insurance_shipping_amount: 'Shipping Insured Amount:',
    ordertosend_insurance_type: 'Insurance Type:',
    ordertosend_insurance_disclaimer_extra: 'If your parcel is lost/damaged, delayed or detained by customs, and you purchased parcel insurance when submitting the goods, we will provide compensation based on the actual shipping cost and the actual value of the goods, up to the insurance amount. You can click to view: ',
    ordertosend_insurance_disclaimer_extra_link: 'Insurance Compensation Description',
    ordertosend_insurance_disclaimer: 'Disclaimer:',
    ordertosend_insurance_disclaimer_1: 'Delay Insurance Disclaimer: Parcel delays that caused by the reasons and situation of force majeure factors such as epidemic, bad weather conditions, war (occurs in the origin, transit, and destination country); parcel be inspected by customs, and the recipient does not cooperate with the local customs to clear customs or pay taxes; and the parcel is failed to be delivered or failed to be collected in time due to the recipient\'s reasons after arriving at the delivery point are uncovered in the scope of delay compensation.',
    ordertosend_insurance_disclaimer_2: 'Loss/Damage Insurance Disclaimer: Parcel loss/damage caused by the recipient, and the parcel is returned to the logistics provider\'s overseas warehouse or destroyed by the logistics provider due to the recipient\'s failure to sign for the parcel in time, are uncovered in the scope of compensation for loss/damage.',
    ordertosend_insurance_disclaimer_3: 'Customs Seizure Insurance Disclaimer: Parcel confiscated caused by the recipient\'s failure to cooperate with local customs clearance or tax payment, etc., are uncovered in the scope of customs seizure compensation.',
    center_my_storage_pre_parcel_tip_title: 'Tip:',
    ordertosend_insurance_no_buy_tip: 'I confirm that I do not purchase insurance and I am willing to bear the loss by myself for any delay, loss/damage, customs detention, etc. that may occur!',
    discount_coupon_redemption: 'Discount coupon redemption',
    exchange: 'exchange',
    center_wallet_coupon_please_input_CDK: 'Please enter redeem code',
    center_wallet_coupon_please_input_success: 'Redemption successful',
    coupon: 'Coupon',
};
