//en.js
const en = {
  // 网页title
  'common_title': 'HagoBuy - The Best Taobao Agent Help You Shop,Shipping From China -weidian agent|1688agent – Cross-border E-commerce for wholesale & retail from China to the world, B2B and B2C online marketplace',
  'share_coupon_title': 'HagoBuy - Free 100 yuan no threshold coupon, 8th and 20th get the largest coupon.',
  // 公共提示字段
  'confirm_ok_text': 'Confirm',
  'confirm_cancel_text': 'Cancel',
  'message_content_in_development': 'In development',
  'affix_cart': 'Cart',
  'affix_cart_check_out': 'Check out cart',
  'pagination_page': 'page',
  // app
  'scan_code_download': 'Scan code to download App',
  'scan_code_download_desc': 'Scan the QR code with your phone\'s camera.Shop anytime, shop anywhere!',
  'm_scan_code_download': 'Click to download',
  'm_scan_code_download_desc': 'Shop anytime, shop anywhere!',
  'm_app_title1': 'Buy from China',
  'm_app_desc1': 'all shopping platforms',
  'm_app_title2': 'High-quality Logistics',
  'm_app_desc2': 'cost-friendly and stable international shipping',
  'm_app_title3': 'Accept Multiple Currencies',
  'm_app_desc3': 'popular and convenient payment methods',
  'm_app_title4': 'Customized Shipping',
  'm_app_desc4': 'reliable services to save your cost',
  // 个人中心-首页
  'center_home': 'User Center',
  'center_home_verified': 'Email verified',
  'center_home_un_verified': 'Email not verified, click to verify',
  'center_home_balance': 'Balance',
  'center_home_coupon': 'Coupon',
  'center_home_growth': 'Growth',
  'center_home_exchange': 'Exchange',
  'center_home_pay': 'Top up',
  'center_home_refund': 'Refund',
  'center_home_refund_tool_tip': 'Return to the original payment method',
  // 个人中心-购物车
  'center_cart': 'Cart',
  'center_cart_search': 'Search',
  'center_cart_goods_detail': 'Product Info',
  'center_cart_remark': 'Remark',
  'center_cart_unit_price': 'Unit Price',
  'center_cart_sum': 'Qty',
  'center_cart_amount': 'Amount',
  'center_cart_action': 'Action',
  'center_cart_select_all': 'Select all',
  'center_cart_delete_check': 'Remove Selected',
  'center_cart_settlement_title': 'Select Products {num} piece of merchandise (International freight is not included)',
  'center_cart_settlement': 'Submit',
  'center_cart_empty_text': 'Your cart is currently empty. Reward yourself by going shopping.',
  'center_cart_card_remark_modal_title': 'Commodity note information',
  'center_cart_card_remark_placeholder': 'Fill in your remarks~',
  'center_cart_card_split': 'Split',
  'center_cart_card_delete': 'Delete',
  'center_cart_card_goods_total': 'Total Price:',
  'center_cart_card_domestic_freight': 'Including domestic freight:',
  'center_cart_card_columns_title1': 'Product Name',
  'center_cart_card_columns_title2': 'Product Details',
  'center_cart_card_columns_title3': 'Unit Price',
  'center_cart_card_columns_title4': 'Amount',
  'center_cart_card_columns_title5': 'Action',
  // 个人中心-收藏夹
  'center_favorite': 'Favorites',
  'center_favorite_placeholder': 'Search for favorites~',
  'center_favorite_delete': 'Delete',
  'center_favorite_table_title_goodsname': 'Title',
  'center_favorite_table_title_goodsprice': 'Price',
  'center_favorite_table_title_createtime': 'Create time',
  'center_favorite_table_title_action': 'ACtion',
  'center_favorite_add_cart': 'Add cart',
  'center_history_placeholder': 'Search~',
  // 个人中心-订单
  'center_my_order': 'Order',
  'center_my_order_goodstype': 'GoodsType',
  'center_my_order_status': 'Order status',
  'center_my_order_goods_status': 'Goods status',
  'center_my_order_search_placeholder': 'Order No. / Name of the Goods',
  'center_my_order_td_detail': 'Product Details',
  'center_my_order_td_price': 'Unit Price',
  'center_my_order_td_sum': 'Qty',
  'center_my_order_td_status': 'Order Status',
  'center_my_order_td_service': 'Action',
  'center_my_order_td_pay': 'Total Prices',
  'center_my_order_td_action': 'Handle',
  'center_my_order_combine_select': 'Select all goods',
  'center_my_order_combine_pay': 'Merge payments',
  'center_my_order_combine_waybill': 'Submission of waybill',
  'center_my_order_ordersn': 'Order No.',
  'center_my_order_create_time': 'Create Time',
  'center_my_order_delete': 'Remove Order',
  'center_my_order_pic': 'Goods Detail',
  'center_my_order_note': 'Message',
  'center_my_order_refund': 'Return goods',
  'center_my_order_remark': 'Remark:',
  'center_my_order_qc_picture': 'QC Picture',
  'center_my_order_share_copy_url': 'Copy Link',
  'center_my_order_extra_photo': 'Extra photo',
  'center_my_order_exp_pic_desc': '【Value-added Service】Extra Photo',
  'center_my_order_exp_pic_check': 'View',
  'center_my_order_exp_pic_update': 'Change',
  'center_my_order_exp_pic_pay': 'Pay',
  'center_my_order_exp_pic_cancel': 'Cancel',
  'center_my_order_extra_photo_modal_count': 'Count',
  'center_my_order_extra_photo_modal_requirement_placeholder': 'Please describe the part to be taken in this photo. You can also add a reference image on the right',
  'center_my_order_extra_photo_modal_free_count': 'The rest of this month free extra photo {count}',
  'center_my_order_extra_photo_modal_service_fee': 'Service charge: ￥{fee}.00',
  'center_my_order_domestic_freight': 'Including domestic freight:',
  'center_my_order_to_pay': 'Pay ',
  'center_my_order_cancel_order': 'Cancel payment',
  'center_my_order_edit_order': 'Edit the order',
  'center_my_order_detail': 'Order details',
  'center_my_order_commodity_note': 'Goods Message',
  'center_my_order_empty': 'You don\'t have any orders yet, go to place an order.~',
  'center_my_order_refund_title': 'Goods refund',
  'center_my_order_refund_radio_label': 'Type',
  'center_my_order_refund_radio_return': 'Refund',
  'center_my_order_refund_radio_replace': 'Replace',
  'center_my_order_refund_radio_check_desc': 'Generally takes 3-7 days',
  'center_my_order_refund_reason': 'Reason',
  'center_my_order_refund_placeholder': 'Please select',
  'center_my_order_refund_quota': 'Free goods returns quota：',
  'center_my_order_refund_explanation': 'Return instructions',
  'center_my_order_refund_textarea_placeholder': 'Please enter the content',
  'center_my_order_refund_warning': 'Tips:',
  'center_my_order_refund_checkbox': 'If must, I am willing to bear the shipping fee & service fee for return/exchange.',
  'center_my_order_robot_title': 'Hagobuy autonomous service',
  'center_my_order_exp_info_modal_title': 'Express info',
  'center_my_order_exp_info_table_no': 'Express number',
  'center_my_order_exp_info_table_weight': 'Weight',
  'center_my_order_exp_info_table_volume': 'Volume',
  // 订单-提交运单
  'ordertosend_title': 'Submit Waybill',
  'ordertosend_address': 'Select address',
  'ordertosend_address_add': 'Add address',
  'ordertosend_address_hidden': 'Fold Address',
  'ordertosend_address_show': 'Change Address',
  'ordertosend_address_select_empty': 'Address empty',
  'ordertosend_address_select_btn': 'Add the shipping address',
  'ordertosend_address_arr_empty': 'Your shipping address list is empty, please add the shipping address',
  'ordertosend_address_edit': 'Edit',
  'ordertosend_address_delete': 'Delete',
  'ordertosend_address_columns_consignee': 'Consignee',
  'ordertosend_address_columns_country': 'Country',
  'ordertosend_address_columns_region': 'Region',
  'ordertosend_address_columns_city': 'City',
  'ordertosend_address_columns_street': 'Street address',
  'ordertosend_address_columns_action': 'Action',
  'ordertosend_order': 'Product list',
  'ordertosend_order_table_number': 'Products',
  'ordertosend_order_table_goodsname': 'Goods Name',
  'ordertosend_order_table_goodsnum': 'Qty',
  'ordertosend_order_table_weight': 'Weight(g)',
  'ordertosend_order_table_volume': 'Volume(cm³)',
  'ordertosend_order_table_action': 'Action',
  'ordertosend_order_table_action_tag': 'Remove Tag',
  'ordertosend_order_table_action_tag_tooltip': 'Remove the product\'s tag. The security seal tags and paper tags will be removed if there are any.',
  'ordertosend_order_table_action_packaging': 'Remove Packaging',
  'ordertosend_order_table_action_packaging_tooltip': 'click this button means to check the weight and volume that are removed packaging. However, Hagobuy does not offer this data for products that are with only little packaging since the difference will not be large. Please tick whether to remove packaging/tags for these items on the Parcel Submission page.',
  'ordertosend_order_table_remove_all_tag': 'Remove All Tags',
  'ordertosend_order_table_remove_all_packaging': 'Remove All Packaging',
  'ordertosend_service_config_title': 'Packing details',
  'ordertosend_service_remark': 'Remark',
  'ordertosend_service_remark_placeholder': 'Feel free to leave a note here if you have other requirements',
  'ordertosend_service_free_ro_quota': 'Free times remaining this month',
  'ordertosend_logistics_err_message': 'Your product has been removed from the shelf or has already been submitted in another shipment. The parcel cannot be submitted normally this time. Please check the status of the product and submit it again.',
  'ordertosend_logistics': 'Choose logistics',
  'ordertosend_logistics_estimate_card_detail': 'Details',
  'ordertosend_logistics_estimate_card_select': 'Select',
  'ordertosend_change_select': 'Reroute',
  'ordertosend_insurance_buy': 'Buy Insurance',
  'ordertosend_insurance_no_buy_tip': 'I confirm that I do not purchase insurance and I am willing to bear the loss by myself for any delay, loss/damage, customs detention, etc. that may occur!',
  'ordertosend_insurance_fee': 'Insurance fee:',
  'ordertosend_insurance_rate': 'Insurance rate:',
  'ordertosend_insurance_product_amount': 'Product Insured Amount:',
  'ordertosend_insurance_shipping_amount': 'Shipping Insured Amount:',
  'ordertosend_insurance_type': 'Insurance Type:',
  'ordertosend_insurance_disclaimer_extra': 'If your parcel is lost/damaged, delayed or detained by customs, and you purchased parcel insurance when submitting the goods, we will provide compensation based on the actual shipping cost and the actual value of the goods, up to the insurance amount. You can click to view: ',
  'ordertosend_insurance_disclaimer_extra_link': 'Insurance Compensation Description',
  'ordertosend_insurance_disclaimer': 'Disclaimer:',
  'ordertosend_insurance_disclaimer_1': 'Delay Insurance Disclaimer: Parcel delays that caused by the reasons and situation of force majeure factors such as epidemic, bad weather conditions, war (occurs in the origin, transit, and destination country); parcel be inspected by customs, and the recipient does not cooperate with the local customs to clear customs or pay taxes; and the parcel is failed to be delivered or failed to be collected in time due to the recipient\'s reasons after arriving at the delivery point are uncovered in the scope of delay compensation.',
  'ordertosend_insurance_disclaimer_2': 'Loss/Damage Insurance Disclaimer: Parcel loss/damage caused by the recipient, and the parcel is returned to the logistics provider\'s overseas warehouse or destroyed by the logistics provider due to the recipient\'s failure to sign for the parcel in time, are uncovered in the scope of compensation for loss/damage.',
  'ordertosend_insurance_disclaimer_3': 'Customs Seizure Insurance Disclaimer: Parcel confiscated caused by the recipient\'s failure to cooperate with local customs clearance or tax payment, etc., are uncovered in the scope of customs seizure compensation.',
  'ordertosend_estimate_weight': 'Estimated Parcel Weight',
  'ordertosend_risks': 'Reminder: Please note the risks before submitting.',
  'ordertosend_risks_tax': 'Tax Warning',
  'ordertosend_risks_tax_tooltip': 'There will have risk of parcel being taxed during the customs clearance. If you receive a tax notice, please clear the customs and pay the taxes, or an expensive fee of parcel return might incur.',
  'ordertosend_risks_logistics': 'Delivery Notice',
  'ordertosend_risks_logistics_tooltip': 'Some routes do not have overseas re-delivery or return service, the parcel returned to the logistics provider\'s overseas warehouse will not be rescheduled for delivery. Please pay attention to the logistics information and sign for the parcel in time.',
  'ordertosend_estimate_weight_tip': 'Since currently parcel is not packed and the real weight of the package is uncertain , we can only roughly estimate the parcel weight. After the parcel is packed, the real weight will be updated, then any excess payment shall be refunded and any deficient shall be repaid.',
  'ordertosend_submit': 'Submit',
  // 个人中心-仓库
  'center_my_storage': 'Warehouse',
  'center_my_storage_search_placeholder': 'Search Name/OrderNo.',
  'center_my_storage_td_details': 'Product Details',
  'center_my_storage_td_time': 'Creation time',
  'center_my_storage_td_num': 'Qty',
  'center_my_storage_td_weight': 'Weight',
  'center_my_storage_td_volume': 'Volume',
  'center_my_storage_td_limit': 'Mail Restriction',
  'center_my_storage_td_action': 'Action',
  'center_my_storage_empty': 'After the order is successfully ordered, the seller will send the goods to the warehouse. After the warehouse receives the goods, you can view and operate the goods on this page.',
  'center_my_storage_pre_parcel': 'Rehearsal Packing',
  'center_my_storage_pre_parcel_tip_title': 'Tip',
  'center_my_storage_pre_parcel_tip_content': 'The Hagobuy pre-packaging service is an additional storage service that costs 20 yuan per time. This service can help you pre-package the products to be sent as required. Pre-packaging provides you with accurate parcel volume/size and accurate weight. We will complete it for you within 24 hours. Would you like to continue?',
  'center_my_storage_pre_parcel_tip_check': 'No more reminders in the future',
  'center_my_storage_pre_parcel_modal_title': 'Rehearsal',
  'center_my_storage_pre_parcel_modal_logistics': 'Intended route',
  'center_my_storage_pre_parcel_modal_no_required': '(not required)',
  'center_my_storage_combine_waybill': 'Submit',
  // 个人中心-预演包裹
  'center_rehearsal': 'Rehearsal',
  'center_rehearsal_all': 'All',
  'center_rehearsal_search_placeholder': 'Enter keywords to search the preview parcel',
  'center_rehearsal_info': 'Rehearsal Info',
  'center_rehearsal_route': 'Preferred Shipping Method',
  'center_rehearsal_weight': 'Weight',
  'center_rehearsal_volume': 'Volume',
  'center_rehearsal_service': 'Value-added',
  'center_rehearsal_status': 'Status',
  'center_rehearsal_action': 'Action',
  'center_rehearsal_parcel_number': 'Rehearsal No.:',
  'center_rehearsal_submit_time': 'Submit time',
  'center_rehearsal_delete': 'Delete',
  'center_rehearsal_cancel': 'Cancel',
  'center_rehearsal_refund': 'Refund',
  'center_rehearsal_submit_parcel': 'Rehearsal Result',
  'center_rehearsal_submit_parcel_submit': 'Confirm and Submit',
  'center_rehearsal_details': 'Details',
  'center_rehearsal_result_tip': 'You can submit the parcel directly according to the weight of the wrapped parcel.',
  'center_rehearsal_result_tip_submit': 'Submit parcel',
  'center_rehearsal_empty_text': 'Before your product is packed, the system is unable to obtain the accurate weight and volume. Therefore, you can obtain the accurate weight and volume of the parcel by purchasing a pre-packaged package on the [My Warehouse] page.',
  'center_rehearsal_pkg_list': 'Parcels list',
  'center_rehearsal_pkg_list_sn': 'Parcel number',
  'center_rehearsal_pkg_list_weight': 'Weight',
  'center_rehearsal_pkg_list_volume': 'Volume',
  // 个人中心-浏览记录
  'center_history': 'Histories',
  // 个人中心-我的包裹
  'center_my_pack': 'Parcel',
  'center_my_pack_all': 'All',
  'center_my_pack_search_placeholder': 'Enter the keyword to search the waybill',
  'center_my_pack_table_info': 'Parcel Info',
  'center_my_pack_table_weight': 'Weight(g)',
  'center_my_pack_table_volume': 'Volume(cm³)',
  'center_my_pack_table_send_fee': 'Shipping Fee',
  'center_my_pack_table_mailing_method': 'Shipping Method',
  'center_my_pack_table_status': 'status',
  'center_my_pack_table_action': 'Action',
  'center_my_pack_ordersn': 'SN: ',
  'center_my_pack_submit_time': 'Submit time',
  'center_my_pack_address': 'Address of delivery:',
  'center_my_pack_delete': 'Remove',
  'center_my_pack_preview': 'Preview',
  'center_my_pack_view_more': 'View more',
  'center_my_pack_share_coupon': 'Share coupon',
  'center_my_pack_receipt': 'Confirm receipt',
  'center_my_pack_comment': 'Comment',
  'center_my_pack_comment_modal_title': 'Your comment information',
  'center_my_pack_comment_empty_desc': 'No comment yet',
  'center_my_pack_pay': 'Pay',
  'center_my_pack_cancel': 'Cancel waybill',
  'center_my_pack_server_fee': 'Including packaging fee:',
  'center_my_pack_insurance_fee': 'Including insurance fee:',
  'center_my_pack_pic': 'Qc picture',
  'center_my_pack_note': 'Message',
  'center_my_pack_detail': 'Parcel details',
  'center_my_pack_empty': 'After successful payment of the parcel order, the order will enter the "Parcel" page, and we will arrange shipping of your goods.',
  'center_my_pack_parcel_message': 'Parcel Message',
  'center_my_pack_parcel_receipt_title': 'Confirming receipt means that you have received the parcel and then click Confirm. May I ask if you have received the parcel? If not received, please click cancel.',
  'center_my_pack_logistics_modal_title': 'Logistics information',
  'center_my_pack_logistics_no_news': 'No news yet',
  'center_my_pack_logistics_international_logistics': 'International logistics',
  'center_my_pack_logistics_no_phone': 'No phone',
  'center_my_pack_logistics_synchronization_time': 'Sync Time',
  'center_my_pack_logistics_no_data': 'The carrier has not updated the trajectory yet',
  'center_my_pack_logistics_waybill_logistics': 'Waybill logistics',
  'logistics_status_not_found': 'Not Found',
  'logistics_status_info_received': 'Info Received',
  'logistics_status_in_transit': 'In Transit',
  'logistics_status_expired': 'Expired',
  'logistics_status_available_for_pickup': 'Available For Pickup',
  'logistics_status_out_for_delivery': 'Out For Delivery',
  'logistics_status_delivery_failure': 'Delivery Failure',
  'logistics_status_delivered': 'Delivered',
  'logistics_status_exception': 'Exception',
  'logistics_sub_status_not_found_other': 'The carrier did not return the information',
  'logistics_sub_status_not_found_invalid_code': 'Invalid Code',
  'logistics_sub_status_info_received': 'Info Received',
  'logistics_sub_status_in_transit_picked_up': 'Picked Up',
  'logistics_sub_status_in_transit_other': 'Other situations',
  'logistics_sub_status_in_transit_departure': 'Departure',
  'logistics_sub_status_in_transit_arrival': 'Arrival',
  'logistics_sub_status_delivery_failure_no_body': 'Delivery Failure No Body',
  'logistics_sub_status_delivery_failure_security': 'Security reasons',
  'logistics_sub_status_delivery_failure_rejected': 'Rejection of parcels',
  'logistics_sub_status_delivery_failure_invalid_address': 'Invalid Address',
  'logistics_sub_status_exception_returning': 'Returning',
  'logistics_sub_status_exception_returned': 'Returned',
  'logistics_sub_status_exception_no_body': 'Recipient information exception',
  'logistics_sub_status_exception_security': 'Security reasons',
  'logistics_sub_status_exception_damage': 'Damage to goods',
  'logistics_sub_status_exception_rejected': 'Rejected',
  'logistics_sub_status_exception_delayed': 'Delayed',
  'logistics_sub_status_exception_lost': 'Lost',
  'logistics_sub_status_exception_destroyed': 'Destroyed',
  'logistics_sub_status_exception_cancel': 'Logistics were canceled',
  'logistics_sub_status_delivered_other': 'Your package has been successfully signed',
  'center_my_pack_parcel_no': 'Parcel number',
  'center_my_pack_parcel_weight': 'Weight',
  'center_my_pack_parcel_volume': 'Volume',
  'center_my_pack_parcel_expressno': 'Express no',
  // 包裹详情
  'pack_detail_back': 'Back my parcel',
  'pack_detail_create_time': 'Parcel create time',
  'pack_detail_before_pic_desc': 'Photo Caption',
  'pack_detail_before_pic_desc1': 'Photos are photos before packing, so you can see if things exist and avoid controversy. Not the final packaging. The final effect is subject to the package you received.',
  'pack_detail_before_pic_desc2': 'If you require to remove the shoebox packaging when packing, we will remove it as required. We will try our best to compress the volume for you. If you think the volume is too large, you can put forward a reconsideration, and we will help you check.',
  'pack_detail_phone': 'Phone No.',
  'pack_detail_zip_code': 'Zip code',
  'pack_detail_delivery_address': 'Address of delivery',
  'pack_detail_goods_info': 'Parcel item list',
  'pack_detail_columns_numbering': 'Numbering',
  'pack_detail_columns_info': 'Goods Info',
  'pack_detail_columns_weight': 'Weight',
  'pack_detail_columns_volume': 'Volume',
  'pack_detail_columns_status': 'Status',
  //个人中心-退款/售后
  'center_my_refund': 'Returns',
  // 个人中心-评论
  'center_my_comment': 'Comment',
  // 个人中心-资产
  'center_my_property': 'Wallet',
  // 个人中心-资产-余额
  'center_wallet_balance': 'Balance',
  'center_wallet_balance_available_balance': 'Available balance:',
  'center_wallet_balance_payment': 'Top up',
  'center_wallet_balance_refund': 'Refund',
  'center_wallet_balance_refund_tool_tip': 'Return to the original payment method',
  'center_wallet_balance_modal_title': 'Enter or select a top up amount',
  'center_wallet_balance_modal_tip': 'You can enter or select a top up amount',
  'center_wallet_balance_modal_btn': 'Go to top up',
  'center_wallet_balance_detail': 'Balance detail',
  'center_wallet_balance_table_time': 'Date',
  'center_wallet_balance_table_operate': 'Operation',
  'center_wallet_balance_table_description': 'Description',
  'center_wallet_balance_table_amount': 'Amount',
  'center_wallet_balance_table_balance': 'Balance',
  // 个人中心-资产-优惠券
  'center_wallet_coupon': 'Coupon',
  'center_wallet_coupon_please_input_CDK': 'Please enter redeem code',
  'center_wallet_coupon_conversion': 'Exchange',
  'center_wallet_coupon_available': 'Available Coupon',
  'center_wallet_coupon_used': 'Coupon Used',
  'center_wallet_coupon_expired': 'Coupon Expired',
  'center_wallet_coupon_cart_limited_more': 'Min . fee >',
  'center_wallet_coupon_cart_limited_use': 'Freight',
  'center_wallet_coupon_cart_no_threshold': 'No threshold',
  'center_wallet_coupon_cart_use_type': 'Applicable channel: ',
  'center_wallet_coupon_cart_use_now': 'Use now',
  'center_wallet_coupon_empty_text': 'You don\'t have the coupon yet',
  'center_wallet_coupon_empty_code': 'Please enter the correct redemption code',
  'center_wallet_coupon_exchange_success': 'Successful exchange',
  // 个人中心-资产-充值记录
  'center_wallet_recharge': 'Top up',
  'center_wallet_recharge_record': 'Top up record',
  'center_wallet_recharge_table_number': 'Number',
  'center_wallet_recharge_table_date': 'Accounting date',
  'center_wallet_recharge_table_denomination': 'Denomination',
  'center_wallet_recharge_table_actual_payment': 'Actual payment',
  'center_wallet_recharge_table_remark': 'Remark',
  'center_wallet_recharge_table_status': 'Top-up status',
  'center_wallet_recharge_table_way': 'Transaction Method',
  // 个人中心-资产-汇款记录
  'center_wallet_remit': 'Remit',
  'center_wallet_remit_record': 'Remit record',
  'center_wallet_remit_table_create_time': 'Create time',
  'center_wallet_remit_table_payname': 'Account name',
  'center_wallet_remit_table_way': 'Pay name',
  'center_wallet_remit_table_money': 'Amount pay',
  'center_wallet_remit_table_status': 'status',
  'center_wallet_remit_table_handle_time': 'Handle time',
  'center_wallet_remit_table_description': 'Description',
  // 个人中心-资产-可退款列表
  'center_wallet_refund': 'Refund',
  'center_wallet_refund_title': 'Available Refund',
  'center_wallet_refund_table_number': 'Transaction No.',
  'center_wallet_refund_table_available_amount': 'Available amount',
  'center_wallet_refund_table_success_time': 'Accounting date',
  'center_wallet_refund_table_way': 'Transaction Method',
  'center_wallet_refund_table_action': 'Action',
  'center_wallet_refund_table_action_refund': 'Refund',
  'center_wallet_refund_modal_title': 'Refund Application',
  'center_wallet_refund_modal_rmb_label': 'Refund Amount(CNY)',
  'center_wallet_refund_modal_remark_label': 'Refund instructions',
  'center_wallet_refund_modal_remark_placeholder': 'Please fill in your refund statement',
  'center_wallet_refund_modal_desc1': 'Maximum refund amount this time CNY',
  'center_wallet_refund_modal_desc2': 'After the application succeeds it will be transferred to the original account of your original payment method.',
  // 个人中心-资产-退款记录
  'center_wallet_refund_record': 'Refund record',
  'center_wallet_refund_record_table_create_time': 'Apply Time',
  'center_wallet_refund_record_table_refund_type': 'Refund Type',
  'center_wallet_refund_record_table_refund_amount': 'Refund Amount',
  'center_wallet_refund_record_table_transaction_no': 'Transaction No.',
  'center_wallet_refund_record_table_remark': 'Description',
  'center_wallet_refund_record_table_status': 'Status',
  // 个人中心-资产-退货列表
  'center_wallet_goods_refund': 'Goods refund',
  'center_wallet_goods_refund_title': 'Goods refund record',
  'center_wallet_goods_record_table_goods': 'Goods info',
  'center_wallet_goods_record_table_amount': 'Amount',
  'center_wallet_goods_record_table_creation': 'Creation time',
  'center_wallet_goods_record_table_cause': 'Reason',
  'center_wallet_goods_record_table_state': 'State',
  'center_wallet_goods_record_table_action': 'Action',
  // 个人中心-咨询
  'center_my_consult': 'Enquiry',
  // 个人中心-站内信
  'center_inmail': 'Station message',
  // 个人中心-账户设置
  'center_account': 'Account',
  // 个人中心-账户设置-个人信息
  'center_account_profile': 'Personal information',
  'center_account_profile_avatar': 'Avatar',
  'center_account_profile_name': 'Nick name',
  'center_account_profile_gender': 'Gender',
  'center_account_profile_birth': 'Birthday',
  'center_account_profile_bio': 'Bio',
  'center_account_profile_email': 'Email',
  'center_account_profile_form_upload': 'Upload',
  'center_account_profile_edit': 'Edit',
  'center_account_profile_privilege': 'My privilege',
  // 个人中心-账户设置-收货地址
  'center_account_address': 'Shipping address',
  'center_account_address_add': 'Add the shipping address',
  'center_account_address_add_tip1': 'You have created',
  'center_account_address_add_tip2': 'shipping addresses',
  'center_account_address_columns_title1': 'Addressee',
  'center_account_address_columns_title2': 'Full address',
  'center_account_address_columns_title3': 'Action',
  'center_account_address_action_edit': 'Edit',
  'center_account_address_action_delete': 'Delete',
  'center_account_address_action_default': 'Default Address',
  'center_account_address_empty': 'You have not added the shipping address, please add the shipping address.',
  'center_account_address_form_consignee': 'Recipient',
  'center_account_address_form_first_name': 'First Name',
  'center_account_address_form_last_name': 'Last Name',
  'center_account_address_form_consignee_name': 'name',
  'center_account_address_form_country': 'Region',
  'center_account_address_form_input_country': 'Please input Country',
  'center_account_address_form_input_state': 'Please input State',
  'center_account_address_form_input_city': 'Please input City',
  'center_account_address_form_detailed_address': 'Street address',
  'center_account_address_form_detailed_detail': 'enter apartment number, street/road address, etc.',
  'center_account_address_form_zip_code': 'Zip code',
  'center_account_address_form_phone': 'Phone No.',
  'center_account_address_form_default': 'Default Address',
  'center_account_address_form_address_tip': 'The street address must be accurate to the house number, otherwise it will result in delivery failure!',
  'center_account_address_form_zip_tip': 'Please confirm again that the zip code and address match accurately, otherwise it will result in delivery failure!',
  'center_account_address_form_info_tip': 'Please confirm again that the zip code and address match accurately, otherwise it will result in delivery failure!',
  // 个人中心-账户设置-安全
  'center_account_security': 'Account security',
  'center_account_security_username': 'User name:',
  'center_account_security_email': 'Email:',
  'center_account_security_edit_email': 'Edit email',
  'center_account_security_edit_email_modal_title': 'Change Email',
  'center_account_security_edit_email_modal_tip': 'You are changing your email',
  'center_account_security_edit_email_modal_current_email': 'Current email:',
  'center_account_security_edit_email_modal_new_email': 'New email',
  'center_account_security_edit_email_modal_captcha': 'Verification Code',
  'center_account_security_edit_email_modal_get_captcha': 'Get Verification Code',
  'center_account_security_edit_email_modal_confirm': 'Confirm',
  'center_account_security_modify_title': 'Modify Password',
  'center_account_security_modify_tip': 'A higher-leveled password makes your account safer. It is recommended to change your password regularly containing numbers and letters beyond 6 digits.',
  'center_account_security_modify_password': 'Modify Password',
  'center_account_security_modify_password_back': 'Back',
  'center_account_security_modify_password_label1': 'Login Password',
  'center_account_security_modify_password_label2': 'New Password',
  'center_account_security_modify_password_label3': 'Repeat Password',
  'center_account_security_modify_password_submit': 'Submit',
  // 个人中心-账户设置-设备管理
  'center_account_device': 'Device management',
  'center_account_device_bulk_revoke': 'Batch Revocation',
  'center_account_device_info': 'Device info',
  'center_account_device_position': 'Position',
  'center_account_device_login_time': 'Last login time',
  'center_account_device_action': 'Action',
  'center_account_device_current_session': 'current session',
  'center_account_device_reovke_session': 'Revoke Access',
  'center_account_revoke_record': 'Do you want to revoke access?',
  'center_account_revoke_record_content': 'The account information of this device will be revoked.',
  // 个人中心-账户设置-信用卡地址
  'center_account_bill': 'Card billing address',
  // 个人中心-自定义功能
  'center_custom': 'Custom',
  'center_custom_photo': 'Extra photo template',
  'center_custom_photo_desc': 'Learn to use this function, when filling in the "fine photo" content, it will become easier',
  'center_custom_photo_add_tmpl': 'Adding templates',
  'center_custom_photo_table_name': 'Photo template name',
  'center_custom_photo_table_count': 'Count',
  'center_custom_photo_table_action': 'Action',
  'center_custom_photo_tmpl_name': 'Photo template name:',
  'center_custom_modal_rules_title': 'Please enter template name',
  'center_custom_photo_tmpl_count': 'Number of photos',
  'center_custom_photo_tmpl_requirement': 'Photo requirements',
  'center_custom_photo_tmpl_requirement_placeholder': 'Only one photo request can be input, such as taking a recent photo of logo, measuring the size of bracelet, etc.',
  'center_custom_photo_add_tmpl_requirement': 'Add',
  'center_custom_photo_add_tmpl_requirement_err_msg': 'Please enter the photo requirements',
  'center_custom_photo_empty_text': 'Did not find your fine photo template,',
  'center_custom_photo_empty_text_click': 'To add a fine photo template',
  //个人中心-活动
  'center_activity': 'activity',
  // 个人中心-推广联盟
  'center_affiliates': 'Affiliates',
  'center_affiliates_bonus_earned': 'Bonus Earned',
  'center_affiliates_qr_tip': 'The users who registered from your QR code or Link will be bonded as your affiliate users.',
  'center_affiliates_copy_link': 'Copy',
  'center_affiliates_edit_link': 'Edit',
  'center_affiliates_modal_custom_code': 'Custom affiliates code',
  'center_affiliates_modal_rules_custom_code': 'Please input custom affiliates code',
  'center_affiliates_bonus_able': 'Available bonus balance',
  'center_affiliates_withdraw': 'Withdraw',
  'center_affiliates_withdraw_record': 'Record',
  'center_affiliates_unsettled_balance': 'Unsettled amount',
  'center_affiliates_unsettled_balance_tooltip': 'Commissions for all orders that have not been confirmed as received. Orders will be verified within 30-60 days, after which the commission will be transferred to your balance account.',
  'center_affiliates_received_bonus': 'Bonus earned',
  'center_affiliates_received_bonus_tooltip': 'The order has been completed and the commission has been transferred to your balance account.',
  'center_affiliates_details': 'Details',
  'center_affiliates_invited_num': 'Number of invited',
  'center_affiliates_check': 'Check',
  'center_affiliates_finish_order': 'Recommended order',
  'center_affiliates_finish_order_tooltip': 'The total number of waybills generated by the friend you recommended. When the waybill is completed, you will be able to receive a commission.',
  'center_affiliates_bonus_withdraw_title': 'Bonus withdraw',
  'center_affiliates_bonus_type': 'Collection type',
  'center_affiliates_bonus_available': 'Available bonus balance',
  'center_affiliates_bonus_amount': 'Amount withdrawn',
  'center_affiliates_privilege': 'My Privilege',
  'center_affiliates_bonus_rate': 'Bonus Rate',
  'center_affiliates_tooltip_title': 'What is Bonus Rate?',
  'center_affiliates_tooltip_content': 'When your affiliate users have received their parcels, HagoBuy will issue you the reward of the parcel shipping fee* Bonus Rate.',
  'center_affiliates_credit': 'Credit',
  'center_affiliates_affiliate_program': 'What is a Affiliate Program?',
  'center_affiliates_affiliate_program_content': 'HagoBuy is a sharing and earning project initiated by all users. Whether you are an individual or a merchant, join a HagoBuy promoter, invite new people to register on HagoBuy and successfully purchase on behalf of you, he/she will become your exclusive user, and each of his/her international logistics consumption will bring you cash rebates, and the rebate amount can be As high as one million yuan, there is no ceiling.',
  'center_affiliates_bonus_calculated': 'How is my bonus calculated?',
  'center_affiliates_bonus_calculated_content': 'Once you become a member, your account will immediately have a 3.5% rebate rate. The more international logistics freight users you invite to register, the more bonuses you will receive and the higher your rebate rate will be. When the bonus reaches a certain amount, you can apply for withdrawal or use it to deduct any service fees on the HagoBuy platform.',
  'center_affiliates_promote_free': 'How to promote for free?',
  'center_affiliates_promote_free_content': 'Copy your promotion link or the promotion link obtained by clicking share on the product page and send it to your friends. When they visit and register, they will become your exclusive users.',
  // 登陆注册
  'account_login': 'Account Login',
  'login': 'Login',
  'sign_up': 'Sign Up',
  'free_sign_up': 'Free Sign Up',
  'forget_password': 'Forget Password?',
  'account_sign_up': 'Account Sign Up',
  'refer_account': 'Existing Account?',
  'please_select_area': 'Please select region',
  'please_select_not_found_placeholder': 'Manual filling',
  'please_input_user_name': 'Please enter your username',
  'please_input_emil': 'Please enter your email',
  'please_input_password': 'Please enter your password',
  'affcode': 'Invitation code (optional)',
  'captcha': 'Captcha',
  'click_refresh_captcha': 'Click to refresh the captcha',
  'login_tab1': 'Happy China Buy',
  'login_tab2': 'Easy to send worldwide',
  'login_tab3': 'Hagobuy professional bulk transportation solutions',
  'sign_agree': 'I have read and agree',
  'sign_agreement1': '《HagoBuy User registration protocol》',
  'sign_and': 'and',
  'sign_agreement2': '《Privacy Statement》',
  'sign_modal_title': 'Registration Successful',
  // 首页
  'index_slogan': 'HAPPY SHOPPING IN CHINA EASY DELIVERY WORLDWIDE',
  'index_tab_slogan1': 'Professional Consolidation Solutions',
  'index_tab_slogan2': 'Efforts to meet the needs of the industry, the price is more favorable',
  'index_purchasing': 'PURCHASING',
  'index_purchasing_title': 'DOMESTIC PLATFORM PURCHASING',
  'index_purchasing_desc': 'TAOBAO/WESHOP1688/JINGDONG',
  'index_save_money': 'SAVE MONEY',
  'index_save_money_title': 'NEWCOMERS SIGN UP TO GET $105 SUPER GIFT PARCEL!',
  'index_save_money_desc': 'PURCHASE IS REDUCED, AND THE TRANSFER IS MORE AFFORDABLE',
  'index_transhipment': 'TRANSHIPMENT',
  'index_transhipment_title': 'MULTICHANNEL OPERATION FOR10 YEARS! FAIR PRICE. SERVICE REST ASSURED!',
  'index_transhipment_desc': 'EXCELLENT GLOBAL TRANSSHIPMENT SERVICES',
  'index_solution1_title': 'Purchase Orders',
  'index_solution2_title': 'Ship To Warehouse',
  'index_solution3_title': 'Quality Check',
  'index_solution4_title': 'Global Shipping',
  'index_solution1_desc': 'Hagobuy agent team can help you purchase all the online & offline products in China. With pasting a product link to make an order, and we will provide a full range of best-in-class services after.',
  'index_solution2_desc': 'You can purchase products from different sellers with us, and these products will be shipped to the Hagobuy warehouse in China.',
  'index_solution3_desc': 'After your products arrived in Hagobuy warehouse, quality check of products will be provided with defections, size, colors, and etc. You will have a caring after-sales service guarantee in Hagobuy.',
  'index_solution4_desc': 'You can freely choose products in your warehouse and submit them into one parcel, ship it to your home by choosing a reliable logistics provider provided by Hagobuy.',
  'index_solution_slogan1': 'One-stop forwarding worldwide',
  'index_solution_slogan2': 'Make cross-border shopping easier',
  'index_search': 'search',
  'index_search_placeholder': 'Taobao,Tmall,1688,JD,Weidian Product URL or Keywords',
  // 顶边栏
  'header_nav_item_home': 'Home',
  'header_nav_item_shopping': 'Shopping Agent',
  'header_nav_item_forwarding': 'Forwarding',
  'header_nav_item_fill_buy': 'Fill & Buy',
  'header_nav_item_affiliates': 'Affiliates',
  'header_language': 'English',
  'header_help_center': 'Help Center',
  'header_please_select_language': 'Please Select Language',
  'header_please_select_cur': 'Please select a currency',
  'herder_center': 'User Center',
  'header_my_order': 'Order',
  'header_my_package': 'Parcel',
  'header_transfer_order': 'Transfer order',
  'header_warehouse': 'Warehouse',
  'header_account_setting': 'Account',
  'header_exit': 'Log out',
  'header_login': 'Log in',
  'header_sign_up': 'Sign Up',
  'herder_shopping_cart': 'Shopping cart',
  'herder_input_placeholder': 'Taobao,Tmall,1688,JD,Weidian Product URL or Keywords',
  'herder_estimate': 'Estimate',
  'header_bj_time': 'Beijing Time',
  // user底边栏
  'footer_user_tab': 'Happy China buy Easy to send the worldwide',
  // 公告栏
  'tip_news': 'Announcement',
  'tip_more': 'More',
  // 运费估算
  'estimate_shipping_fee': 'Shipping Fee Estimation',
  'estimate_describe1': 'Cooperate with many international express companies, Ultra low freight discount',
  'estimate_destination_country': 'Destination',
  'estimate_destination': 'Sent to HagoBuy warehouse',
  'estimate_select_destination': 'Please select destination country',
  'estimate_weight': 'Weight',
  'estimate_enter_weight': 'Please enter weight',
  'estimate_warehouse': 'Warehouse',
  'estimate_xiamen_warehouse': 'Xiamen Warehouse',
  'estimate_length': 'Length',
  'estimate_width': 'Width',
  'estimate_height': 'Height',
  'estimate_goodstype': 'GoodsType',
  'estimate_select_goodstype': 'Please select goods type',
  'estimate_search': 'Search',
  'estimate_describe2': 'All logistics services for non HagoBuy proprietary lines are provided by third-party logistics providers, who will adjust the freight price according to the market conditions. HagoBuy will notify in advance if there is any price change. To provide the ultimate service experience, HagoBuy can negotiate with third-party logistics providers on your behalf if you encounter problems in logistics services.',
  'estimate_gentle_reminder': 'Gentle Reminder',
  'estimate_message1': 'Please select the country you want to send to, the system checks whether there is a line can send goods to your country.',
  'estimate_message2': 'Please fill in the correct weight of the goods!',
  'estimate_message3': 'Please select warehouse',
  'estimate_message4': 'Please select the mail product type!',
  'estimate_insurance_title': 'This shipping line covers the following service when insurance is purchased:',
  'estimate_shipping': 'Shipping Fee',
  'estimate_tooltip_text': 'charges by the volumetric weight ',
  'estimate_tooltip_text_else': 'parcel length, width, and height information is needed',
  'estimate_tooltip_vw': 'Volume Weight:',
  'estimate_tooltip_title1': 'The volumetric weight and charges whichever is the greater',
  'estimate_tooltip_title2': 'This shipping method charges by comparing the actual weight',
  'estimate_tooltip_title3': 'parcel volume formulate: Length*Width*Height*1000/',
  'estimate_aging': 'Transit Time',
  'estimate_cost_detail': 'Settlement detail',
  'estimate_cost_international_shipping': 'International Shipping',
  'estimate_cost_operate_fees': 'Operation Fee',
  'estimate_cost_first_freight': 'First Freight',
  'estimate_cost_renewed_freight': 'Continued Freight',
  'estimate_cost_process_fees': 'Carrier Processing Fee',
  'estimate_cost_fuel_surcharge': 'Fuel Surcharge',
  'estimate_standard': 'Settlement standard',
  'estimate_standard_first_price': 'First Price',
  'estimate_standard_renewed_price': 'Continued Weight Price',
  'estimate_line_characteristics': 'Line characteristics',
  'estimate_line_view': 'See Details',
  'estimate_line_fold': 'Fold',
  'estimate_mailing_restrictions': 'Mailing restrictions',
  // 帮助中心
  'help_title1': 'Hi! Can I help you?',
  'help_search_answer': 'Please enter the keywords you want to search',
  'help_search': 'Search',
  'help_title2': 'Can\'t find the answer you need? ',
  'help_contact_customer_service': 'Contact customer service',
  'help_title3': 'to solve the problem!',
  'help_common_problem_classification': 'Daily Questions',
  'help_search_keywords': 'Search keywords:',
  // 确认订单页面
  'carttoorder_confirm_order': 'Confirm Order',
  'carttoorder_confirm_product_info': 'Confirm Product Information',
  'carttoorder_back_cart': 'Back to cart and edit',
  'carttoorder_product_detail': 'Product Details',
  'carttoorder_remark': 'Remark',
  'carttoorder_unit_price': 'Unit Price',
  'carttoorder_amount': 'Amount',
  'carttoorder_add_service': 'Value-added Services',
  'carttoorder_total': 'Total',
  'carttoorder_clause1': '《Prohibited Items Statement》',
  'carttoorder_clause2': '《Service Terms and Users Management》',
  'carttoorder_clause3': '《Return/Exchange Service》',
  'carttoorder_clause4': '《Disclaimer》',
  'carttoorder_agree_check': 'I have read and agreed',
  'carttoorder_reminder': 'Friendly reminder:',
  'carttoorder_reminder_text': 'After submitting the order and paid, please kindly wait for the seller to send, submit an international parcel order once stored at the warehouse.',
  'carttoorder_back': 'Back',
  'carttoorder_submit_order': 'Submit Order',
  'carttoorder_cart_remark_title': 'Commodity note information',
  'carttoorder_cart_remark': 'Fill in your remarks~',
  'carttoorder_cart_tip_prompt': 'No prompt',
  'carttoorder_extra_photo': 'Extra Photo',
  'carttoorder_photo_modal_count_tip': 'Reminder: A photo only provides a detail of a product',
  'carttoorder_photo_modal_tmpl': 'Photo template:',
  'carttoorder_total_price': 'Total Price:',
  'carttoorder_domestic_freight': 'Domestic Freight',
  'carttoorder_shop_total': 'Shop Total',
  'carttoorder_total_service_fee': 'Value-added fee:',
  'carttoorder_total_tip1': 'Total',
  'carttoorder_total_tip2': 'Int\'l shipping fee not included',
  // 支付
  'pay_title': 'Checkout Counter',
  'pay_current_country': 'Current Country',
  'pay_current_open_channels': 'Available Payment Options',
  'pay_coupon': 'Coupon',
  'pay_coupon_empty_code': 'Please enter the correct redemption code',
  'pay_coupon_exchange_success': 'Successful exchange',
  'pay_coupon_input': 'Please enter the coupon code',
  'pay_coupon_exchange': 'exchange',
  'pay_coupon_no_use': 'No coupon',
  'pay_coupon_denomination': 'Denomination',
  'pay_coupon_type': 'Type',
  'pay_coupon_indate': 'Valid period',
  'pay_coupon_unavailable': 'A coupon that is currently unavailable',
  'pay_payment_original_total': 'Original price',
  'pay_payment_total': 'Payable',
  'pay_payment_processing_fee': 'Handling Fee',
  'pay_payment_actual_amount': 'Actual payable',
  'pay_payment_payment_tip': 'Reminder: First recharge to the balance, can be more convenient and quick settlement.',
  'pay_payment_confirm': 'Confirm payment',
  'pay_payment_modal_new_page_payment': 'New page payment',
  'pay_payment_modal_finish_payment': 'Payment completed',
  'pay_payment_modal_cancel_text': 'Continue to pay',
  'pay_payment_modal_title': 'Reminder: Please perform payment operations on the new page that opens. The payment is not completed, please do not close this window',
  'pay_payment_modal_tip1': 'If the payment has been successfully completed, please click the payment completed',
  'pay_pay_success': 'Payment Completed',
  'pay_pay_success_tip': 'Your order will be processed within 6 working hours (except for some third-party platforms\' orders)',
  'pay_pay_success_tip_title': 'Please pay attention to the following:',
  'pay_pay_success_desc_title1': 'The goods will not be sent to you directly, but first to HAGOBUY warehouse, you need to submit the parcel yourself',
  'pay_pay_success_desc1': 'After the goods being stored in our warehouse, you can select the orders in "User Center-My Warehouse", submit the parcel, and choose logistics to pay the international freight.',
  'pay_pay_success_desc_title2': 'Pay attention to the information on the site',
  'pay_pay_success_desc2': 'During order purchasing process, you will be notified via internal message once any issue occurs.',
  'pay_pay_success_btn_buy': 'Shopping More',
  'pay_pay_success__check_order': 'My Order',
  // 商品详情
  'item_details_not_fount_tip1': 'This product may not exist. ',
  'item_details_not_fount_tip_url': 'Please visit the above link to confirm.',
  'item_details_not_fount_tip': 'If it is valid according to the original link, please the page and {load} or {fill}',
  'item_details_reload': 'reload',
  'item_details_manual_fill': 'fill in shopping',
  'item_details_enter_shop': 'Enter shop',
  'item_details_product_link': 'Product Link',
  'item_details_enter_shop_tooltip': 'Click here to check all products in this shop',
  'item_details_refresh': 'Refresh',
  'item_details_discount_time': 'Remaining time of activity',
  'item_details_discount': 'Shop Discount',
  'item_details_send_discount': 'Deduct Int\'l Shipping',
  'item_details_send_discount_end': 'Shipping Fee Deduction Expire Time',
  'item_details_discount_rules': 'Activity rules',
  'item_details_discount_rules_desc': 'Submit this product before the deadline to send international packages, can offset ({curSendMoney}) international freight, offset up to the package freight {maxSendDiscount}, can be used in addition to other credit products, can be used with package coupons and system discounts.',
  'item_details_sales': 'Sales',
  'item_details_buy_tip': 'After payment, we will purchase for you from 09:00-18:00 (UTC+8).',
  'item_details_post_fee1': 'Domestic freight {post} Send to {warehouse} ,We provide free quality inspection photos',
  'item_details_post_fee2_span1': 'After you confirm the goods, choose to send them out by international express.',
  'item_details_post_fee2_span2': 'Delivery Estimation',
  'item_details_in_stock': 'In stock',
  'item_details_quantity': 'Quantity',
  'item_details_remarks': 'Remarks',
  'item_details_tooltip_title': 'Please read and agree before operation',
  'item_details_risk_agree': 'Agreed',
  'item_details_statement_top': 'HagoBuy will only purchase for you according to the link you enter. If you have any doubts regarding your orders, reach out to our online service.',
  'item_details_statement_bottom': 'The displayed products are from third-party platforms, and HagoBuy only provides information search, purchasing, and delivery services. Therefore, HagoBuy cannot identify the quality and/or authenticity of the goods, and using HagoBuy\'s purchasing service means you accept the above risks by default.',
  'item_details_buy': 'Buy now',
  'item_details_add_cart': 'Add to Shopping Cart',
  'item_details_qc_tip': 'Growth value is equal to or greater than {point}, you can see the product reference map. Your current growth value is insufficient.',
  'item_details_repository_quantity_empty_message': 'The product is out of stock and cannot be purchased.',
  'item_details_share': 'Affiliate Share',
  'item_details_add_favorite': 'Collect',
  'item_details_del_favorite': 'Unfavorite',
  'item_details_arrival_day': 'Average days of arrival',
  'item_details_day': 'days',
  'item_details_weight': 'Weight',
  'item_details_volume': 'Volume',
  'item_details_un_weight': 'De-packing weight',
  'item_details_un_volume': 'De-packing volume',
  'item_details_sold_out_text': 'We regret to inform you that we are unable to purchase this product for you as it is no longer available.',
  'item_details_sold_out_recommend_title': 'We recommend you:',
  'item_details_sold_out_recommend_span1': 'Search this product from other stores or platforms',
  'item_details_sold_out_recommend_span2': 'If you have any questions, please consult ',
  'item_details_sold_out_recommend_span2_service': 'customer service',
  'item_details_goods_store': 'Hot commodity recommendation',
  'item_details_tab1': 'Product details',
  'item_details_tab2': 'Service and Commitment',
  'item_details_tab3': 'Delivery & Payment',
  'item_details_delivery_span1': 'Shopping is divided into two stages: Chinese purchasing agent and international shipping, including two payments. You are recommended to do an international freight assessment before placing an order',
  'item_details_delivery_span2': 'Stage 1: You need to pay for the cost of the goods and the logistics costs of the goods in China, HagoBuy will provide you with the purchase service. The purchased goods will be sent to the HagoBuy transit warehouse for temporary storage, and the quality inspection service of the goods will be performed at the same time. There is a free storage period of 180 days after the goods are put into storage. You can purchase multiple products and package them before sending them internationally, which saves money',
  'item_details_delivery_span3': 'Phase 2: Pack the goods and generate a parcel order, pay the international logistics cost of the order, and then the parcel can be internationally transported. {shop} > {estimate}',
  'item_details_delivery_span3_shop': 'Guide',
  'item_details_delivery_span3_estimate': 'Shipping Calculation widget',
  'item_details_tab4': 'Shopping Notes',
  'item_details_shop_note_embargo': 'Embargo',
  'item_details_shop_note_embargo_span1': '·No tobacco, alcohol or contraband',
  'item_details_shop_note_embargo_span2': 'Contraband includes, but is not limited to, the following goods: Swiss Army knife, full set of kitchen knives, kitchen knives, Paper cutting/paper cutting/letter opener, gardening/knife/scissors/saw, thread remover/thread remover, pure fruit and vegetable juice, inflatable lighter, wine, putty knife, cheese/Western cheese, hairy crab, bamboo sword/wood knife, saber card/universal knife card, skate shoes, other outdoor Tools, magnetic components, Swiss Army knife, end milling cutter, carving knife, smoke mark/smoke card, diamond bell/diamond pestle/knife, seeds, etc.',
  'item_details_shop_note_restriction': 'Purchase restriction',
  'item_details_shop_note_restriction_span': '·Medicine, liquid, paste goods and cosmetic powder belong to the goods restricted from export by the Chinese Customs. Please consult before ordering',
  'item_details_shop_note_restriction_service': '【Customer service】',
  'item_details_shop_note_warm': 'Warm reminder',
  'item_details_shop_note_warm_span': '【About Customs logistics】 Some countries or regions are sensitive to special commodities according to the differences in customs policies, so there will be embargoes, purchase restrictions, logistics route restrictions and volume and weight restrictions.',
  // 商品列表
  'item_shop_tab1': 'Default sort',
  'item_shop_tab2': 'Sales',
  'item_shop_tab3': 'Reputation',
  'item_shop_tab4': 'Price from high to low',
  'item_shop_tab5': 'Price from low to high',
  'item_shop_sales': 'Sales',
  'item_shop_load_fail': 'Sorry, the request failed. Please try again later.',
  'item_shop_refresh': 'Refresh',
  // 手动填单
  'item_notfound_step1': 'Fill and Submit Product Information',
  'item_notfound_step2': 'Pay for product and shipping fee',
  'item_notfound_step3': 'Waiting for seller to send',
  'item_notfound_goods_details': 'Product Details',
  'item_notfound_goodsurl_label': 'Product Link',
  'item_notfound_goodsurl_placeholder': 'Enter a product link starts with http:// or https://',
  'item_notfound_goodsname_label': 'Product Name',
  'item_notfound_goodsname_placeholder': 'Please enter product name',
  'item_notfound_skuname_label': 'Specifications',
  'item_notfound_skuname_placeholder': 'To more accurately purchase products for you, please leave specifications such as color/size here.',
  'item_notfound_goodsimg': 'Commodity images',
  'item_notfound_goodsimg_upload': 'Upload Image',
  'item_notfound_goodsimg_reupload': 'Reupload',
  'item_notfound_goodsimg_uploading': 'The picture is being uploaded',
  'item_notfound_goodsimg_uploading_success': 'Image uploaded successfully',
  'item_notfound_goodsimg_uploading_fail': 'Image uploaded failed, ',
  'item_notfound_goodsimg_upload_limit': 'Image under 3MB only (please upload GIF, JPG and PNG form)',
  'item_notfound_goodsremark_label': 'Product Notes',
  'item_notfound_goodsremark_placeholder': 'Write a message ONLY when you have special requirements regarding this order\'s purchasing.',
  'item_notfound_fee': 'Fee',
  'item_notfound_fee_tooltip': 'Hagobuy cannot identify the price of the goods on the third party platform, so you need to enter the price below. If you are not clear about the price of the goods, you can fill in 1 yuan to place an order. After receiving the order, the Hagobuy buyer will contact the merchant and then initiate the payment to you.',
  'item_notfound_goodsprice_label': 'Unit Price',
  'item_notfound_goodsprice_tips': 'If the price of the product is unknown, you can fill in 1 yuan to wait for the purchase supplement.',
  'item_notfound_goodsnum_label': 'Qty',
  'item_notfound_warehouseId_label': 'Send to',
  'item_notfound_sendprice_label': 'Domestic Shipping',
  'item_notfound_sendprice_tip': 'Please fill in the seller\'s shipping cost to Hagobuy warehouse',
  'item_notfound_total_label': 'Total',
  'item_notfound_total_tooltip': 'Total amount = Cost of goods + freight to warehouse conversion standard (based on RMB)',
  'item_notfound_total_tip': 'International shipping cost is not involved and will be charged separately. ',
  'item_notfound_total_estimate': ' Shipping Fee Estimate',
  'item_notfound_agree_tip': 'On this page, you are submitting third-party products (such as Xianyu, Xiaohongshu, Bilibili, Yupoo, etc.). Hagobuy can only help you find the linked sellers for product consultation, purchasing for you, and arranging third-party logistics delivery services. Hagobuy cannot distinguish the quality or authenticity of goods, please note this before purchasing.',
  'item_notfound_agreement1': 'Shopping Agent Guidance',
  'item_notfound_agreement2': 'After Sales Service',
  'item_notfound_agree_checkbox': 'Agreed',
  'item_notfound_quick_buy': 'Buy Now',
  'item_notfound_add_to_cart': 'Add To Cart',
  // 邮件安全
  'email_nav_had_account': 'Already Registered,',
  'email_nav_login': 'Log in',
  'email_nav_back_home': 'Return HagoBuy',
  'email_activate_active_modal_title': 'To protect your account security, please verify your email.',
  'email_activate_active_modal_confirm': 'To verify',
  'email_activate_active': 'Activate an account',
  'email_activate_in_active': 'Mailbox active',
  'email_activate_success': 'Mailbox activation succeeded',
  'email_activate_login_by_email': 'You can log in to Hagobuy using the registered email address',
  'email_activate_failure': 'Mailbox activation failure',
  'email_activate_back_home': 'Back Homepage',
  'email_activate_tip': 'Click to send an email to verify your email address',
  'email_activate_send': 'Send email',
  'email_forget_account_security': 'Account Safety',
  'email_forget_associated': 'Please enter the email connected to your account',
  'email_forget_email': 'Email',
  'email_forget_send': 'Submit',
  'email_reset_password': 'Reset Password',
  'email_reset_input_password': 'Please enter your password',
  'email_reset_new_password': 'New Password',
  'email_reset_confirm_password': 'Repeat Password',
  'email_reset_submit': 'Commit',
  // 转运
  'forwarding_header_tutorial': 'Tutorial of Forwarding Service',
  'forwarding_header_title': 'Add a forwarding order',
  'forwarding_header_back_order': 'Return to my order',
  'forwarding_warehouse_title': 'Select the warehouse to send',
  'forwarding_warehouse_label': 'Select warehouse',
  'forwarding_warehouse_address': 'Warehouse Address',
  'forwarding_warehouse_copy_all': 'Copy all information',
  'forwarding_warehouse_info_consignee': 'Receiver:',
  'forwarding_warehouse_info_region': 'Region:',
  'forwarding_warehouse_info_city': 'City:',
  'forwarding_warehouse_info_street': 'Address:',
  'forwarding_warehouse_info_postcode': 'Post/ZIP code:',
  'forwarding_warehouse_info_phone': 'Mobile:',
  'forwarding_warehouse_tips': 'FriendLy Tips:',
  'forwarding_warehouse_tip_content': 'If you are sending a parcel to a Hagobuy warehouse, please do not disclose the delivery number to anyone. The delivery Number is the unique identification to prove that the parcel belongs to you. Enter your delivery number in [Tracking Number] below and the warehouse will automatically associate the parcel with your order after receiving the parcel',
  'forwarding_order_title': 'Information of your parcel sent to {warehouse} warehouse',
  'forwarding_order_express_number': 'Tracking Number',
  'forwarding_order_express_number_placeholder': 'Please enter the tracking number',
  'forwarding_order_parcel_name': 'Goods information',
  'forwarding_order_parcel_name_placeholder': 'Goods name, quantity, etc',
  'forwarding_order_express_tip': 'Please fill in the domestic express tracking number sent to Hagobuy warehouse and ask the sender for this tracking number information.',
  'forwarding_order_add_goods': 'Add tracking number',
  'forwarding_agreement_read_agree': 'I have read and agree',
  'forwarding_agreement': '《HagoBuy parcel Transfer inspection Rules and Service Agreement》',
  'forwarding_footer_cancel': 'Cancel',
  'forwarding_footer_submit': 'Submit',
  'forwarding_message_warning_empty': 'Please enter domestic tracking number (letters and/or numbers)',
  'forwarding_message_warning_empty_information': 'Please enter the goods information',
  'forwarding_message_warning_agreement': 'Please read and agree to the Service Agreement!',
  'forwarding_message_success_submit': 'Transfer order submitted successfully!',
  // 推广联盟
  'affiliates_back_center': 'Return to center',
  // 首页
  'affiliates_home': 'Home',
  // 关联用户
  'affiliates_user': 'Affiliate user',
  'affiliates_user_invited': 'Invited user:',
  'affiliates_user_table_title_username': 'Username',
  'affiliates_user_table_title_order_count': 'Number of orders',
  'affiliates_user_table_title_sendorder_count': 'Number of waybills',
  'affiliates_user_table_title_amount_all': 'Total amount of waybills',
  'affiliates_user_table_title_amount_settled': 'Settled waybills amount',
  'affiliates_user_table_title_amount_unsettled': 'Unsettled waybills amount',
  'affiliates_user_table_title_join_time': 'Registration time',
  // 奖金明细
  'affiliates_bonus': 'Bonus details',
  'affiliates_bonus_empty_desc': 'You haven\'t invited users yet,',
  'affiliates_bonus_empty_desc_invite': 'Go invite',
  'affiliates_bonus_table_title_type': 'Type',
  'affiliates_bonus_table_title_username': 'Associated user',
  'affiliates_bonus_table_title_amount': 'Amount',
  'affiliates_bonus_table_title_balance': 'Balance',
  'affiliates_bonus_table_title_remark': 'Remark',
  'affiliates_bonus_table_title_create_time': 'Create Time',
  'affiliates_bonus_FAQ': 'FAQ',
  // 提现记录
  'affiliates_withdraw': 'Withdrawal record',
  'affiliates_withdraw_table_title_type': 'Type',
  'affiliates_withdraw_table_title_account': 'Account',
  'affiliates_withdraw_table_title_amount': 'Amount',
  'affiliates_withdraw_table_title_remark': 'Remark',
  'affiliates_withdraw_table_title_status': 'Status',
  'affiliates_withdraw_table_title_create_time': 'Submission time',
  // 等级相关
  'affiliates_level': 'My level',
  'affiliates_level_record': 'Record of experience value',
  'affiliates_level_table_title_type': 'Type',
  'affiliates_level_table_title_exp': 'Exp',
  'affiliates_level_table_title_exp_after': 'Total Exp',
  'affiliates_level_table_title_level': 'Level',
  'affiliates_level_table_title_create_time': 'Acquisition time',
  // 推广页
  'promote_sign_up_btn': 'Sign up to get $105 coupon',
  'promote_banner_title': 'Hagobuy is offering a special promotion: 100RMB no-threshold freight discount coupon with just 200 lucky winners!',
  'promote_banner_desc': 'You can now claim one and enjoy shipping！​Redemption method: User Center - Wallet - Coupons - Exchange',
  'promote_banner_btn_code': 'THE CODE: ',
  'promote_banner_btn_desc': 'Applicable to newly registered users only',
  'promote_banner_btn_confirm_content': 'Promo code has been copied, click Confirm to jump to the registration page.',
  'promote_about_title': 'Who We Are',
  'promote_about_desc1': 'Hagobuy is a brand-new, legal shopping agent that helps global users purchase goods from domestic e-commerce platforms such as Taobao, 1688, and JD.com.',
  'promote_about_desc2': 'With high-quality and low-cost commodities, preferential shipping policy, ultra-low exchange rate, and high-quality customer service, we will create a more convenient, affordable, and efficient shopping platform for global customers.',
  'promote_about_desc3': 'Join us now and get in touch with your favorite brands!',
  'promote_about_purchasing': 'Purchasing',
  'promote_about_transport': 'Transport',
  'promote_purchasing_title': 'Purchasing Service Process',
  'promote_purchasing_process1': 'Submit the purchased goods',
  'promote_purchasing_process2': 'Pay for the goods',
  'promote_purchasing_process3': 'Purchase from HagoBuy to the warehouse',
  'promote_purchasing_process4': 'Quality inspection, weighing and warehousing',
  'promote_purchasing_process5': 'Submit the international waybill and pay the freight',
  'promote_purchasing_process6': 'Confirm receipt of good reviews',
  'promote_advantage_title': 'Why choose Hagobuy',
  'promote_advantage_item_title1': 'Free service fee',
  'promote_advantage_item_desc1': 'Free multi-platform massive search service, all orders will be processed and released within 1 working day',
  'promote_advantage_item_title2': 'Warehousing service',
  'promote_advantage_item_desc2': 'With up to 180 days of free storage, there\'s no need to rush! Add more orders and pay for shipping only once. You\'ll have more time to shop and save money at the same time.',
  'promote_advantage_item_title3': 'Easy payment',
  'promote_advantage_item_desc3': 'Don\'t worry about international currency issues, support paypal, credit card and other mainstream payments.',
  'promote_advantage_item_title4': 'Repacking',
  'promote_advantage_item_desc4': 'We bubble wrap products for protection, remove unnecessary items like shoe-boxes, & more! We repack your orders with protection!',
  'promote_advantage_item_title5': 'Quality Check',
  'promote_advantage_item_desc5': 'Worrying about damaged and broken products arriving at your home? Our dedicated team checks the quality of your orders, following your specifications.',
  'promote_advantage_item_title6': 'Insurance service',
  'promote_advantage_item_desc6': 'Buy insurance for your parcel, you can get full compensation at most, so you can buy worry-free!',
  'promote_partner': 'Business Partner',
  'promote_difference_title': 'What makes Hagobuy different',
  'promote_difference_item_title1': 'lower exchange rate',
  'promote_difference_item_desc1': 'You will find that we offer lower exchange rates! This means that you can buy various products from the Chinese market at a more favorable price, which is so cost-effective that you will be pleasantly surprised!',
  'promote_difference_item_title2': 'Inexpensive',
  'promote_difference_item_desc2': 'Cooperate with many high-quality suppliers and purchase directly from the source, eliminating intermediate links and bringing you lower commodity prices. Whether you love fashion or practical daily necessities, Hagobuy can let you buy what you want at a cheaper price!',
  'promote_difference_item_title3': 'Super low shipping price',
  'promote_difference_item_desc3': 'We are well aware of the importance of shipping costs to shopping, so Hagobuy cooperates with world-class logistics companies to deliver to your home in a more economical and affordable way. Our shipping price is lower than other platforms, allowing you to save more while shopping!',
  'promote_difference_item_title4': 'First class customer service',
  'promote_difference_item_desc4': 'We are proud to have a professional, friendly customer service team ready to provide you with an exceptional service experience. No matter what questions or needs you have, we will always meet your requests with a smile and patience.',
  'promote_customers_title': 'What Our Customers Says',
  'promote_problem_title': 'Common Problem',
  'promote_sidebar_title': 'SIGN UP TO GET $105 NOW',
  'promote_sidebar_btn': 'Sign up',
  //分享赢免单
  'activity_steps': 'Simple Steps',
  'activity_shopping': 'Shopping With Hagobuy',
  'activity_share_experience': 'Share Experience/Suggestions',
  'activity_submit_share_url': 'Submit Your Sharing',
  'activity_check': 'Hagobuy Verifying',
  'activity_receive_reward': 'Receive Your Reward',
  'activity_apply_btn': 'Apply Here',
  'activity_apply_reward_btn': 'My Reward',
  'activity_form_desc': 'Share your Hagobuy shopping experience, win up to 100% cash rewards of your orders amount and parcel amount!',
  'activity_apply_reward': 'Apply Reward',
  'activity_share_link': 'Sharing Link',
  'activity_social_media': 'Social Media',
  'activity_related_parcel': 'Related Parcel',
  'activity_input_warn': 'enter the link that you made for sharing Hagobuy experience',
  'activity_choose_platform': 'choose platform',
  'activity_cancel_btn': 'Cancel',
  'activity_no_pack': 'No parcel records yet. Please dont forget to share when you receive the haul!',
  'activity_choose': 'choose parcel',
  'activity_apply_list': 'My Reward',
  'activity_apply_Num': 'Application NO',
  'activity_apply_Platform': 'Platform',
  'activity_apply_Link': 'Link',
  'activity_apply_Related_Parcel': 'Related Parcel',
  'activity_apply_Reward': 'Reward',
  'activity_apply_Status': 'Status',
  'activity_check_more': 'View More',
  'activity_confirm_btn': 'Confirm',
  'activity_reward_users': 'Users Who Already Won',
  'activity_user': 'user',
  'activity_rewarded': 'rewarded',
  'activity_date': 'date',
  'activity_more_rewarded_user': 'Users Who Won Rewards Already',
  'activity_rules': 'Description',
  'activity_reward_steps': 'The process of winning this reward:',
  'activity_share_reasons': 'Why does Hagobuy offer rewards for social media sharing?',
  'activity_check_rules': 'What is Hagobuy\'s review standard?',
  'activity_get_what': 'What can you gain from sharing?',
  'activity_warnInfo': 'We want to kindly remind you that If you delete the sharing link within 3 months after getting the reward, Hagobuy will permanently disqualify your future application.',
  'activity_if_helpful': 'Whether the shared content is helpful:',
  'activity_if_influence': 'Whether the output has influence:',
  'activity_reward_steps_content_one': '1) After receiving your Hagobuy parcel, make your unboxing sharing, video sharing is preferred!',
  'activity_reward_steps_content_two': '2) Submit the sharing link on Hagobuy Parcel Page, find the Apply Reward button! Please submit a social media sharing link about your own Hagobuy shopping experience, link should be able to be redirected to the content page.',
  'activity_reward_steps_content_three': '3) Hagobuy verifies review manually and issues your rewards!',
  'activity_reward_steps_content_four': 'We hope that when users share, they have already completed the experience of placing orders and receiving hauls. Such sharing can provide a higher-level reference for users who have not experienced cross-border shopping or haven\'t experienced Hagobuy. Of course, you are welcome to share something that held you back in your shopping process to help better Hagobuy optimize, and the whole team attaches great importance to this.',
  'activity_reward_steps_content_five': 'If you have posted your sharing on multiple social platforms, you can submit the proudest link to Hagobuy for review. If you are just a beginner-level social platform sharer, don\'t worry; Hagobuy manually reviews these shares. As long as you put your heart into it and made it with effort, we are your fans!',
  'activity_reward_steps_content_six': 'Considering that sharing on social platforms takes a certain amount of time to gain attention, we will review it in {hour} after you submit the link (weekdays only) to ensure that your sharing has enough time to be discovered by more people. Therefore, the reward you get would be higher.',
  'activity_reward_steps_content_six_hour': '72 hours',
  'activity_reward_steps_content_seven': 'You work hard, and you earn cash. Up to 100% cash reward (the amount of your orders and parcel shipping fee) is awaiting you.We are open to hearing anything good to keep it up. For the bad parts, we also regard them as suggestions/feedback, and we seek help from our users to optimize. Finally, beyond grateful, we want to offer some financial reward. However, your reward application will likely be rejected if you fill out invalid links, or you will be rewarded $1-$5 if you\'re posting some QC sharings only.',
  'activity_order_sn': 'Waybill number',
  'activity_order_fee': 'Waybill cost',
  'activity_order_time': 'Waybill time',
  'share_get_free': 'Share to Get Free Orders',
  'to_share': 'Share',
  'activity_reward_remark': 'Remark',
  'activity_reward_text': 'The more popular the video/post (such as more views, likes, etc.), the higher the reward',
  'activity_get_reward_way': 'The secret method of getting high reward video/post',
  'activity_article_link': '(Click here to learn)',
  'activity_reddit_desc': 'You can use the "Share W2C" function on the order page (which includes the title, price, purchase link, QC photo, etc. of the product) to publish your post content by copying the corresponding graphics and text to your reddit edit box!',
  // 分享优惠卷
  'share_coupon_title1': 'Invite Friends',
  'share_coupon_title2': 'Get a large coupon',
  'share_coupon_not_open_desc': 'No threshold freight red envelope, click to receive',
  'share_coupon_opened_head1': 'Congratulations on getting',
  'share_coupon_opened_head2': 'It can be deducted from the freight. Go ahead and place your order',
  'share_coupon_opened_coupon_title': 'Surprise red envelope',
  'share_coupon_share_btn': 'Sharing',
  'share_coupon_use_btn': 'To use',
  'share_coupon_opened_over_head1': 'Ran out of coupons',
  'share_coupon_opened_over_head2': 'Hagobuy has a coupon for you. Go ahead and place your order',
  'share_coupon_red_packet_empty_text': 'This share coupon has been snatched up ~',
  'share_coupon_red_packet_empty_btn_text': 'Get more coupons',
  'share_modal_title': 'Coupon sharing',
  'share_modal_btn': 'Copy links',
  'share_coupon_signed_user_title': 'How lucky are friends',
  'share_coupon_signed_user_good_luck': 'Best luck',
  'share_coupon_signed_user_luck_empty': 'The best luck hasn\'t come yet. Go ',
  'share_coupon_signed_user_luck_empty_invite': 'invite friends',
  'release_time': 'Release time:'
}

export default en
